import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      bg: "rgb(var(--bg))",
      "accent-bg": "rgb(var(--accent-bg))",
      text: "rgb(var(--text))",
      "text-light": "rgb(var(--text-light))",
      border: "rgb(var(--border))",
      accent: "rgb(var(--accent))",
      "accent-hover": "rgb(var(--accent-hover))",
      "accent-text": "rgb(var(--accent-text))",
      code: "rgb(var(--code))",
      preformatted: "rgb(var(--preformatted))",
      marked: "rgb(var(--marked))",
      disabled: "rgb(var(--disabled))",
      gray: {
        50: "rgb(var(--gray-50))",
        100: "rgb(var(--gray-100))",
        200: "rgb(var(--gray-200))",
        300: "rgb(var(--gray-300))",
        400: "rgb(var(--gray-400))",
        500: "rgb(var(--gray-500))",
        600: "rgb(var(--gray-600))",
        700: "rgb(var(--gray-700))",
        800: "rgb(var(--gray-800))",
        900: "rgb(var(--gray-900))",
        950: "rgb(var(--gray-950))",
      },
      watercourse: {
        50: "rgb(var(--watercourse-50))",
        100: "rgb(var(--watercourse-100))",
        200: "rgb(var(--watercourse-200))",
        300: "rgb(var(--watercourse-300))",
        400: "rgb(var(--watercourse-400))",
        500: "rgb(var(--watercourse-500))",
        600: "rgb(var(--watercourse-600))",
        700: "rgb(var(--watercourse-700))",
        800: "rgb(var(--watercourse-800))",
        900: "rgb(var(--watercourse-900))",
        950: "rgb(var(--watercourse-950))",
      },
    },
  },
  plugins: [],
};
export default config;
